Develop
VazAnton/java-filmorate pull request #25
Opened 2024-03-17 06:24 UTC by VazAnton

2024-03-17 15:54 UTC, avlin87 requested changes
Вы проделали большую работу! 
У вас получился отличный проект и появились навыки работы в команде. 
Исправьте, пожалуйста, комментарии и присылайте на проверку.

2024-03-17 15:54 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/feed/FeedService/FeedService.java
> +public class FeedService {
В классах Service хорошо бы добавить логирование.

2024-03-17 15:54 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService/FilmService.java
>  import ru.yandex.practicum.filmorate.model.Rating;
В классах Service добавь, пожалуйста, логирование.

2024-03-17 15:54 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/review/ReviewService/ReviewService.java
> +public class ReviewService {
В классах Service добавь, пожалуйста, логирование.

2024-03-17 15:54 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService/UserService.java
В классах Service добавь, пожалуйста, логирование.

2024-03-18 13:34 UTC, VazAnton commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
Добавил для каждого класса контроллера

2024-03-18 13:36 UTC, VazAnton commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("/directors")
Провёл рефактор кода, теперь всё разбито по отдельным контроллерам и сервисам

2024-03-18 17:52 UTC, avlin87 approved these changes
Хорошая работа! 
Молодцы, что сделали все задания. 
Здорово, что выбрали усложнённую версию и добавили режиссера в поиск. Вы хорошо разобрались во взаимодействие между слоями сервис контроллер репозиторий.

2024-03-22 10:13 UTC, merged