feat: Написал догику обработки запросов к базовым эндпоинтам по добав…
VazAnton/java-filmorate pull request #5
Opened 2024-01-03 13:01 UTC by VazAnton

…лению и обновлению данных фильмов и пользователей

2024-01-06 15:40 UTC, avlin87 requested changes
Привет, Антон,
работа выглядит хорошо, оставил пару комментариев, смотри, пожалуйста, в пулл реквесте.

2024-01-06 15:40 UTC, avlin87 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +                new Executable() {
```
                new Executable() {
                    @Override
                    public void execute() throws Throwable {
                        filmController.addFilm(film1);
                    }
                }
```
Этот код лучше переписать лямбдой:
`() -> filmController.addFilm(film1)` - так можно получить объект Executable
так получится:
```
ValidationException validationException = assertThrows(
    ValidationException.class,
    () -> filmController.addFilm(film1)
);
```

поправь, пожалуйста, в других местах тоже.

2024-01-06 15:40 UTC, avlin87 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        Film film1 = new Film(1, "Маска", "ыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыы" +
`можно лучше`

Погугли, пожалуйста "lorem generator"
Если возникнет желание, то "ыыыы..." лучше заменить на сгенерированный текст. Функционально ничего не изменится, просто код будет выглядеть более профессионально. Ниже коротко цитата из интернета, "что это вообще такое".

**Lorem**
Текст-"рыба", часто используемый в печати и вэб-дизайне.
Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов.

2024-01-06 16:02 UTC, VazAnton commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +                new Executable() {
Думаю, идея заменить несколько строчек кода на более лаконичные лямбда-выражения и правда достаточно хорошая, чтобы всерьёз задуматься над её реализацией, к тому же среда разработки сама предлагала мне такой вариант, но я пока стараюсь не увлекаться лямбдами там, где аналогичный по смыслу код, записанный без их использования, выглядит для меня недостаточно знакомо, чтобы не бояться заменить его лямбдами. Это для меня пока просто вопрос времени и практики, но само замечание беру на вооружение и исправлю недочёты в ближайшее время

2024-01-07 20:38 UTC, avlin87 approved these changes
Работу принимаю.

2024-01-07 20:38 UTC, avlin87 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +                "главный герой Стэнли Ипкисс случайно находит магическую маску, что дарует ему невероятные суперсилы" +
`можно лучше`
после переноса строки хорошая практика добавлять пробел, чтобы получившаяся строка не соединила два слова.

2024-01-18 13:59 UTC, merged