feat: Добавил БД
VazAnton/java-filmorate pull request #7
Opened 2024-02-26 14:56 UTC by VazAnton

2024-02-26 16:26 UTC, VazAnton commented
Не очень понятно, почему падают тесты, связанные с pom-файлом

2024-02-27 16:23 UTC, avlin87 requested changes
Привет, Антон,
В целом работа выглядит хорошо, но упало 4 теста ru.yandex.practicum.filmorate.UserDbStorageTest
checkGetUserByIdIfUserExist
checkDeleteFriend
checkUpdateUser
checkAddFriend

Почини, пожалуйста, их первым приоритетом.
Остальные комментарии смотри, пожалуйста, ниже.

2024-02-27 16:23 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public Map<String, String> notFoundObjectHandler(final RuntimeException e) {
Лучше написать свое исключение DataNotFoundException чем использовать RuntimeException. Это будет более информативно.

2024-02-27 16:23 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> getFilm(@PathVariable int id) {
Optional хорошо подходит для передачи информации между слоями/классами приложения.
Для endpoit API же лучше воспользоваться **Film**.

2024-02-27 16:23 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Optional<User> getUser(@PathVariable int id) {
Optional хорошо подходит для передачи информации между слоями/классами приложения.
Для endpoit API же лучше воспользоваться **User**.

2024-02-27 16:23 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmDbStorage.class);
`Можно лучше`
Вместо создания переменной можно на класс поставить аннотацию на класс `@Slf4j`.
Эта аннотация автоматически создаст и инициализирует переменную log.

2024-02-28 17:23 UTC, VazAnton commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmDbStorage.class);
Переписал тесты, в коде всё проходит, но тут почему то не собирается, пока не получается разобраться в чём дело

2024-02-29 05:04 UTC, avlin87 requested changes
Добавь, пожалуйста, файл README.md а в него помести картинку схемы бд.
Смотри, пожалуйста, пару новых комментариев ниже.

2024-02-29 05:04 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    public User getUser(@PathVariable int id) {
Аннотации `@PathVariable`, `@RequestBody` применимы при работе с контроллерами.
В Repository эти аннотации ничего не сделают.
Оставь их, пожалуйста, только в контроллерах.

2024-02-29 17:49 UTC, VazAnton commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    public User getUser(@PathVariable int id) {
Проработал комментарии, починил тесты, поправил несколько методов

2024-03-01 01:08 UTC, avlin87 requested changes
Убедись, пожалуйста, что приложение работает правильно. Проверь его дополнительно с помощью тестов Postman: sprint.json.
https://github.com/yandex-praktikum/java-filmorate/blob/add-database/postman/sprint.json

**`Эти же тесты запускаются в GitHub при создании pull request’а. 
Проверьте их локально, прежде чем делать pull request.`**

2024-03-03 07:16 UTC, avlin87 approved these changes
Работу принимаю.

2024-03-04 17:00 UTC, merged